# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: false
language: R
cache: packages

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal1-dev
      - libproj-dev
